PlantillasMVC/Models/ErrorViewModel.cs
using System;

namespace PlantillasMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PlantillasMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PlantillasMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PlantillasMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PlantillasMVC/Controllers/PlantillasController.cs
using Microsoft.AspNetCore.Mvc;
using plantillasDominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rotativa.AspNetCore;
using Newtonsoft.Json;


namespace PlantillasMVC.Controllers
{
    public class PlantillasController : Controller
    {
        private Administrador miAdmin = Administrador.Instancia;

       
        public IActionResult IndexAltaPlantilla()
        {
            string strJson = "[";
            ViewBag.Equipos = miAdmin.Equipos;
            ViewBag.Formaciones = miAdmin.Formaciones;
            int i = 0;
            foreach (Formacion miFormacion in miAdmin.Formaciones)
            {
                if (i == miAdmin.Formaciones.Count - 1)
                {
                    strJson += JsonConvert.SerializeObject(miFormacion);

                }
                else
                {
                    strJson += JsonConvert.SerializeObject(miFormacion) + ",";
                    i++;
                }

            }
            strJson += "]";
            ViewBag.Formaciones = strJson;
            string strJsonf = "[";
            int j = 0;
            foreach (Equipo miEquipo in miAdmin.Equipos)
            {
                if (j == miAdmin.Equipos.Count - 1)
                {
                    strJsonf += JsonConvert.SerializeObject(miEquipo);

                }
                else
                {
                    strJsonf += JsonConvert.SerializeObject(miEquipo) + ",";
                    j++;
                }

            }
            strJsonf += "]";
            ViewBag.Equipos = strJsonf;
            return View();
            //return new ViewAsPdf("IndexAltaPlantilla");
        }
        public IActionResult IndexVerAlineacion()
        {
            string strJsonf = "[";
            int j = 0;
            foreach (Equipo miEquipo in miAdmin.Equipos)
            {
                if (j == miAdmin.Equipos.Count - 1)
                {
                    strJsonf += JsonConvert.SerializeObject(miEquipo);

                }
                else
                {
                    strJsonf += JsonConvert.SerializeObject(miEquipo) + ",";
                    j++;
                }

            }
            strJsonf += "]";
            ViewBag.Equipos = strJsonf;
            return View();
        }
        public IActionResult VerAlineacion(string equipo, string rival)
        {
            Alineacion miAlineacion = miAdmin.AlineacionPorEquipoYRival(equipo, rival);
            ViewBag.Alineacion = JsonConvert.SerializeObject(miAlineacion);

            return View("IndexVerAlineacion");
        }
       
    }
}

PlantillasMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido al creador de Plantillas</h1>
</div>

PlantillasMVC/Views/Plantillas/IndexAltaPlantilla.cshtml
@{
    ViewData["Title"] = "IndexAltaPlantilla";
}
<p id="formaciones">@ViewBag.Formaciones</p>
<p id="equipos">@ViewBag.Equipos</p>
<select id="select-formaciones">
  
</select>
<select id="select-equipos">
</select>
<div class="cancha">
    <div id="players-container">
    </div>
    <form method="post" action="~/Plantilla/AltaAlineacion">

    </form>
</div>
<script>


    let misFormaciones = document.getElementById('formaciones');
    let misEquipos = document.getElementById('equipos');
    let misFormacionesObj = JSON.parse(misFormaciones.innerText);
    let misEquiposObj = JSON.parse(misEquipos.innerText);
    let select = document.getElementById("select-formaciones");
    let selectE = document.getElementById("select-equipos");
    let playersContainer = document.getElementById("players-container")
    let form_seleccionada;
    let equipo_seleccionado;


    misFormaciones.style.display = "none";
    misEquipos.style.display = "none";
    
    function cargarFormaciones() {
        let selectOptions = `<option class ="f-opt" value="null">Formacion</option>`;
        misFormacionesObj.forEach(e => {
            selectOptions += `<option class="f-opt" value="${e.Nombre}">${e.Nombre}</option>`
        })
        select.innerHTML = selectOptions;
    }
    function cargarEquipos() {
        let selectOptions = `<option class ="e-opt" value="null">Equipo</option>`;
        misEquiposObj.forEach(e => {
            selectOptions += `<option class="e-opt" value="${e.Nombre}">${e.Nombre}</option>`
        })
        selectE.innerHTML = selectOptions;
    }

    function renderFormacion() {
        select.addEventListener("change", (e) => {
            playersContainer.innerHTML = "";
            posicionesPorNombre(e.target.value);
            posicionar();
            
        })
    }
    function renderEquipo() {
        selectE.addEventListener("change", (e) => {
            equipoPorNombre(e.target.value);
        })
    }
    function posicion(nombre) {
        let miPos = null;
        let i = 0;
        while (miPos == null && i < form_seleccionada.length) {
            if (form_seleccionada[i].Especifica == nombre) {
                miPos = form_seleccionada[i];
            }
            i++;
        }
        return miPos;
    }
    function posicionar() {
        let posiciones = document.getElementsByClassName("player");
        for (let i = 0; i < posiciones.length; i++) {
            let especifica = posiciones[i].dataset.especifica;
            let miPlayer = posicion(especifica);
            

            let X = () => { if (miPlayer.X == 0) { return "auto" } else { return `${miPlayer.X}` } }

            if (miPlayer.X < 0) {
                posiciones[i].style.setProperty("margin", `auto ${X()*-1}px ${miPlayer.Y}px auto`);
            }
            if (miPlayer.X == 0) {
                posiciones[i].style.setProperty("margin", `auto auto ${miPlayer.Y}px ${X()}`);
            }
            if (miPlayer.X > 0)
            {
                posiciones[i].style.setProperty("margin", `auto auto ${miPlayer.Y}px ${X()}px`);
            }

        }
    }
    function posicionesPorNombre(nombre) {
        let i = 0;
        let miForm = null;
        while (i < misFormacionesObj.length && miForm == null) {
            if (nombre == misFormacionesObj[i].Nombre) {
                miForm = misFormacionesObj[i];
            }
            i++;
        }
        form_seleccionada = miForm.Posiciones;
        let playersAppend = "";

        form_seleccionada.forEach((e,i) => {
            playersAppend = `
                <div data-especifica="${e.Especifica}" class="player" id="a${i+1}">
                    <p class="position">${e.Nombre}</p>
                </div>
                `;
            playersContainer.innerHTML += playersAppend;
         
        })
       
    }
    function equipoPorNombre(nombre) {
        let i = 0;
        let miEquipo = null;
        while (i < misEquiposObj.length && miEquipo == null) {
            if (nombre == misEquiposObj[i].Nombre) {
                miEquipo = misEquiposObj[i];
            }
            i++;
        }
        equipo_seleccionado = miEquipo;
       
    }


    cargarFormaciones();
    cargarEquipos();
    renderEquipo();
    renderFormacion();



  
</script>

PlantillasMVC/Views/Plantillas/IndexVerAlineacion.cshtml
@{
    ViewData["Title"] = "IndexVerAlineacion";
}

<p id="equipos-view">@ViewBag.Equipos</p>
<form method="post" action="~/Plantillas/VerAlineacion">
    <select name ="equipo"id="select-equiposV">
    </select>
    <select name="rival" id="select-equiposR">
    </select>
    <input type="submit" value="Cargar Alineacion">
</form>
<p id="alineacion">@ViewBag.Alineacion</p>
<div class="cancha">
    <div id="players-containerV">
    </div>
   
</div>
<script>
    
    let misEquipos = document.getElementById("equipos-view");
    let misEquiposObj;
    let miAlineacion = document.getElementById("alineacion");
    let miAlineacionObj;
    if (misEquipos.innerText != "") {
        misEquiposObj = JSON.parse(misEquipos.innerText);
        function cargarEquipos() {
            let selectOptions = `<option class ="e-opt" value="null">Equipo</option>`;
            misEquiposObj.forEach(e => {
                selectOptions += `<option class="e-opt" value="${e.Nombre}">${e.Nombre}</option>`
            })
            selectE.innerHTML = selectOptions;
            renderEquipo();
        }
        function cargarRival() {
            let selectOptions = `<option class ="r-opt" value="null">Rival</option>`;
            equipo_seleccionado.Alineaciones.forEach(e => {
                selectOptions += `<option class="r-opt" value="${e.Rival}">${e.Rival}</option>`
            })
            selectR.innerHTML = selectOptions;
            selectR.addEventListener("change", (e) => {
                rival_seleccionado = e.target.value;

            })
        }
        let selectE = document.getElementById("select-equiposV");
        let selectR = document.getElementById("select-equiposR");
        let rival_seleccionado;
        let equipo_seleccionado;
        misEquipos.style.display = "none";



        function renderEquipo() {
            selectE.addEventListener("change", (e) => {
                equipoPorNombre(e.target.value);
                cargarRival();

            })
        }
        function equipoPorNombre(nombre) {
            let i = 0;
            let miEquipo = null;
            while (i < misEquiposObj.length && miEquipo == null) {
                if (nombre == misEquiposObj[i].Nombre) {
                    miEquipo = misEquiposObj[i];
                }
                i++;
            }
            equipo_seleccionado = miEquipo;

        }

        cargarEquipos();
    }
    if (miAlineacion.innerText != "") {
        miAlineacionObj = JSON.parse(miAlineacion.innerText);
        miAlineacion.style.display = "none";
        let playersCont = document.getElementById("players-containerV");

        function renderAlineacion() {
            let playersAppend = "";
            miAlineacionObj.Titulares.forEach((e, i) => {
                playersAppend = `
                <div data-especifica="${e.Posicion.Especifica}" class="player" id="a${i + 1}">
                    <p class="position">${e.Posicion.Nombre}</p>
                    <p class = "player-name">${e.Nombre}</p>
                </div>
                `;
                playersCont.innerHTML += playersAppend;
            })
        }
        renderAlineacion();
        posicionar();
        function posicion(nombre) {
            let miPos = null;
            let i = 0;
            while (miPos == null && i < miAlineacionObj.Formacion.Posiciones.length) {
                if (miAlineacionObj.Formacion.Posiciones[i].Especifica == nombre) {
                    miPos = miAlineacionObj.Formacion.Posiciones[i];
                }
                i++;
            }
            return miPos;
        }
        function posicionar() {
            let posiciones = document.getElementsByClassName("player");
            for (let i = 0; i < posiciones.length; i++) {
                let especifica = posiciones[i].dataset.especifica;
                let miPlayer = posicion(especifica);


                let X = () => { if (miPlayer.X == 0) { return "auto" } else { return `${miPlayer.X}` } }

                if (miPlayer.X < 0) {
                    posiciones[i].style.setProperty("margin", `auto ${X() * -1}px ${miPlayer.Y}px auto`);
                }
                if (miPlayer.X == 0) {
                    posiciones[i].style.setProperty("margin", `auto auto ${miPlayer.Y}px ${X()}`);
                }
                if (miPlayer.X > 0) {
                    posiciones[i].style.setProperty("margin", `auto auto ${miPlayer.Y}px ${X()}px`);
                }

            }
        }
    }
    
</script>

PlantillasMVC/Views/Plantillas/IndexViewPdf.cshtml
@{
    ViewData["Title"] = "IndexViewPdf";
}

<script>document.body.innerHTML = @ViewBag.html</script>

PlantillasMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlantillasMVC</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantillas" asp-action="IndexAltaPlantilla">Crear Plantillas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantillas" asp-action="IndexVerAlineacion">Crear PDF Alineacion</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>